# do this
name: Execute Code Base
on:
  push:
    branches-ignore: [scratch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install vsftpd libncursesw5-dev libtinfo-dev
      - name: Prepare script files
        run: |
           sed -i -e's/\x0D$//' ./*.sh
           chmod +x ./*.sh
      - name: Execute main script file
        run: |
           ./init.sh
           ./script.sh
